### ISSUE TITLE
Using feynson for eikonal propagators?

### ISSUE THREAD

**Issue by vsht** [magv/feynson#3]
Hi Vitaly,

does feynson actually support families with eikonal propagators?

Trying something trivial such as
```
{ {{q*l, l^2-m^2}, {q*l, l^2-m^2}}, {l}, {} }
```
I get
```
[dbg 0.0002s +0.0002s] Family size set: set{2}
[dbg 0.0003s +0.0001s] Preparing family 1
[dbg 0.0003s +0.0000s] > feynman_uf()
[err 0.0004s +0.0001s *] feynman_uf(): denominator #1 (=l*q) is linear in the loop momenta
```

If there is really a limitation, I guess that it must be pure technical, since both the UF-formula and Pak's algorithm are perfectly applicable to linear propagators?

Cheers,
Vlad

**Comment by magv** [comment]
Hi, Vlad. So the linearity check is a overly paranoid. No, there's no limitation here. I've removed this check, this is safe.

There is however a practical problem: some of the linear proparator examples I've seen don't work once  the check if off, in the sense that the system of equations to figure out momenta-space mapping has quadratic and unfactorizable equations -- even though the solutions do exist. If this is the case, some more work on my side is needed to try to make it work better. This work I haven't done yet.

So yeah, try your linear propagator example, and see how it goes.

**Comment by vsht** [comment]
Hi Vitaly,

many thanks for the quick fix! We will let you know should there be any problems with less trivial families.

Cheers,
Vlad
